### ISSUE TITLE
warning: IB Designables: Using class UIView for object with custom class because the class CircleProgressView does not exist

### ISSUE THREAD

**Issue by oligazar** [CardinalNow/iOS-CircleProgressView#32] opened 2016-08-11 12:09 UTC
I was trying to use CircleProgressView in IB. But it doesn't show up and I've got these warnings:
warning: IB Designables: Using class UIView for object with custom class because the class CircleProgressView does not exist
warning: IB Designables: Ignoring user defined runtime attribute for key path "trackWidth" on instance of "UIView". Hit an exception when attempting to set its value: [...]: this class is not key value coding-compliant for the key trackWidth.

**Comment by xrolfex** [comment] 2016-08-11 14:46
Try switching to the identity inspector window, and then remove any user defined runtime attributes. Restart Xcode and see if that fixes the issue.

**Comment by oligazar** [comment] 2016-08-11 22:47
I did it. But with no luck. I'm using xcode 7.3.1. What else can I try?

**Comment by oligazar** [comment] 2016-08-11 23:20
If I add CircleProgressView file directly to the project it works fine. But not from Pods

**Comment by xrolfex** [comment] 2016-09-13 12:27
This is caused by the module name from cocoa pods. It will be fixed today with Xcode 8 and swift 3 release.

**Closed by xrolfex** 2016-09-13 12:27 UTC

**Comment by SoftDev0420** [comment] 2016-09-29 08:10
Hi @xrolfex, any luck for this issue?
