### ISSUE TITLE
ui issue

### ISSUE THREAD

**Issue by lazyjean** [CardinalNow/iOS-CircleProgressView#67] opened 2018-01-09 03:30 UTC
1. drag an UIView to storyboard
2. set class CircleProgressView
3. set Progress property to 1.0
3. tun Rounded Cap on

**Comment by xrolfex** [comment] 2018-01-23 20:12
What is the issue?

**Comment by farshadmb** [comment] 2018-01-24 10:04
@xrolfex track cap and background cap layer overlap eachother

**Comment by mattstrong** [comment] 2018-03-06 05:12
@xrolfex Can this be fixed?

**Comment by xrolfex** [comment] 2018-03-09 13:23
It can be fixed but it would require the a significant change in the structure. Essentially the fill track needs its percentage to be larger when track cap is set. At the moment it time i will put it in the backlog to work. On Going to close this issue for now.

**Closed by xrolfex** 2018-03-09 13:23 UTC

**Comment by KevinQuisquater** [comment] 2018-12-27 21:09
@xrolfex any updates on this issue, by any chance?

Just to clarify the problem, since the issue is badly formatted: if rounded cap is enabled and the track path has a background color, when progress is around 99%-100%, the line overlaps with itself and the rounded arc takes the color of the progress path background, rather than the progress path fill color.

Here's a [screenshot](https://i.imgur.com/KxUnmhy.png) at 100%.
